# Generated by Django 5.1 on 2024-08-28 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0003_alumno_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('empresa', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('url', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
            options={
                'db_table': 'empleo',
            },
        ),
    ]
