# Generated by Django 5.1 on 2024-08-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo',
            name='alumno',
        ),
    ]
