# Generated by Django 5.1 on 2024-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_remove_empleo_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='modalidad',
            field=models.CharField(default='No Registrado', max_length=255),
        ),
    ]
