# Generated by Django 5.1 on 2024-08-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='experiencia',
            table='experiencia_laboral',
        ),
    ]
