# Generated by Django 5.1 on 2024-08-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
