# Generated by Django 5.1 on 2024-08-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_alter_certificado_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificado',
            table='certificado',
        ),
    ]
