# Generated by Django 5.1 on 2024-08-19 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
        ('estados', '0001_initial'),
        ('periodos', '0002_alter_periodo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('linkedin', models.TextField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodos.periodo')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
    ]
