# Generated by Django 5.1 on 2024-08-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
