# Generated by Django 5.1 on 2024-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
