# Generated by Django 5.1 on 2024-08-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grados_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gradoacademico',
            table='grado_academico',
        ),
    ]
