# Generated by Django 5.1 on 2024-08-19 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alter_alumno_correo'),
        ('grados_academicos', '0002_alter_gradoacademico_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('grado_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grados_academicos.gradoacademico')),
            ],
            options={
                'db_table': 'alumno_grado',
            },
        ),
    ]
