# Generated by Django 5.1 on 2024-08-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='titulo_obtenido',
        ),
    ]
