# Generated by Django 5.1 on 2024-08-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educaciones', '0002_remove_educacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='carrera',
            field=models.CharField(default='No Registrado', max_length=100),
        ),
        migrations.AddField(
            model_name='educacion',
            name='tipo_estudio',
            field=models.CharField(default='No Registrado', max_length=60),
        ),
    ]
