# Generated by Django 5.1 on 2024-08-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educaciones', '0003_educacion_carrera_educacion_tipo_estudio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='educacion',
            table='formacion_academica',
        ),
    ]
